AWSTemplateFormatVersion: '2010-09-09'
Description: A QR Code Generating API

Parameters:
  Region:
    Type: String
    Default: us-east-1
  TimeStamp:
    Type: String
  AccountId:
    Type: String
    Default: '{{resolve:secretsmanager:account-id:SecretString:account-id:1}}'
  BranchName:
    Description: github branch name
    Type: String
    Default: master
  RepositoryName:
    Description: github repository name
    Type: String
    Default: qr-generator
  GitHubOwner:
    Type: String
    Default: jmartin432
  Email:
    Type: String
    Default: info@justinlmartin.com
  LambdasBucketName:
    Type: String
    Default: '{{resolve:ssm:qr-generator-lambdas-bucket:1}}'

Resources:
  LambdasBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LambdasBucketName
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  LatestTimeStamp:
    Value: !Ref TimeStamp
